/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.castilho.paranavai.armario.visao;

import com.castilho.paranavai.armario.controle.EditorLoginAdminControladorGUI;
import com.castilho.paranavai.armario.controle.LoginControlador;
import javax.swing.JOptionPane;

/**
 *
 * @author Wesley
 */
public class EditorLoginAdminGUI extends javax.swing.JFrame {

    private final EditorLoginAdminControladorGUI controlador;
    
    /**
     * Creates new form EditorLoginAdminGUI
     */
    public EditorLoginAdminGUI() {
        initComponents();
        setTitle("Login do Administrador");
        this.controlador = new EditorLoginAdminControladorGUI(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelLoginAdmin = new javax.swing.JPanel();
        labelEmailAdmin = new javax.swing.JLabel();
        textEmailAdmin = new javax.swing.JTextField();
        labelSenhaAdmin = new javax.swing.JLabel();
        textSenhaAdmin = new javax.swing.JPasswordField();
        botaoAcessarAdmin = new javax.swing.JButton();
        botaoVoltarPrincipal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelEmailAdmin.setText("SIAPE");

        textEmailAdmin.setText("exemplo@gmail.com");

        labelSenhaAdmin.setText("Senha");

        textSenhaAdmin.setText("jPasswordField1");

        botaoAcessarAdmin.setText("Acessar");
        botaoAcessarAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoAcessarAdminMouseClicked(evt);
            }
        });

        botaoVoltarPrincipal.setText("Voltar");
        botaoVoltarPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoVoltarPrincipalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PainelLoginAdminLayout = new javax.swing.GroupLayout(PainelLoginAdmin);
        PainelLoginAdmin.setLayout(PainelLoginAdminLayout);
        PainelLoginAdminLayout.setHorizontalGroup(
            PainelLoginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelLoginAdminLayout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(PainelLoginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(PainelLoginAdminLayout.createSequentialGroup()
                        .addComponent(botaoVoltarPrincipal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoAcessarAdmin))
                    .addComponent(labelSenhaAdmin, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEmailAdmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textEmailAdmin, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textSenhaAdmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );
        PainelLoginAdminLayout.setVerticalGroup(
            PainelLoginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelLoginAdminLayout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(labelEmailAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textEmailAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelSenhaAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textSenhaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(PainelLoginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAcessarAdmin)
                    .addComponent(botaoVoltarPrincipal))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelLoginAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelLoginAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAcessarAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAcessarAdminMouseClicked
        LoginControlador controleLogin = new LoginControlador();
        String email = this.textEmailAdmin.getText();
        String senha = String.copyValueOf(this.textSenhaAdmin.getPassword());
        String respostaLoginAdmin = controleLogin.verificaAdmin(email, senha);
        
        if(respostaLoginAdmin.equals("Sucesso no login")){
            JOptionPane.showMessageDialog(null, "Bem vindo ao sistema!");
            this.controlador.navegarParaMenuAdmin();
            dispose();
        }
        else{
            JOptionPane.showMessageDialog(null, "Acesso negado, verifique as credenciais!");
        }
    }//GEN-LAST:event_botaoAcessarAdminMouseClicked

    private void botaoVoltarPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoVoltarPrincipalMouseClicked
        this.controlador.navegarParaPrincipal();
        dispose();
    }//GEN-LAST:event_botaoVoltarPrincipalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditorLoginAdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditorLoginAdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditorLoginAdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditorLoginAdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditorLoginAdminGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelLoginAdmin;
    private javax.swing.JButton botaoAcessarAdmin;
    private javax.swing.JButton botaoVoltarPrincipal;
    private javax.swing.JLabel labelEmailAdmin;
    private javax.swing.JLabel labelSenhaAdmin;
    private javax.swing.JTextField textEmailAdmin;
    private javax.swing.JPasswordField textSenhaAdmin;
    // End of variables declaration//GEN-END:variables
}