/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.castilho.paranavai.armario.visao;

import com.castilho.paranavai.armario.controle.EditorLoginAlunoControlador;
import com.castilho.paranavai.armario.controle.LoginControlador;
import javax.swing.JOptionPane;

/**
 *
 * @author Wesley
 */
public class EditorLoginAlunoGUI extends javax.swing.JFrame {

    private final EditorLoginAlunoControlador controlador;
    
    /**
     * Creates new form LoginGUI
     */
    public EditorLoginAlunoGUI() {
        
        initComponents();
        setTitle("Login do aluno");
        this.controlador = new EditorLoginAlunoControlador(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelLoginAluno = new javax.swing.JPanel();
        labelEmailAluno = new javax.swing.JLabel();
        textEmailAluno = new javax.swing.JTextField();
        labelSenhaAluno = new javax.swing.JLabel();
        textSenhaAluno = new javax.swing.JPasswordField();
        botaoAcessarAluno = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelEmailAluno.setText("Email");

        textEmailAluno.setText("exemplo@gmail.com");

        labelSenhaAluno.setText("Senha");

        textSenhaAluno.setText("jPasswordField1");

        botaoAcessarAluno.setText("Acessar");
        botaoAcessarAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoAcessarAlunoMouseClicked(evt);
            }
        });

        botaoVoltar.setText("Voltar");
        botaoVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoVoltarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PainelLoginAlunoLayout = new javax.swing.GroupLayout(PainelLoginAluno);
        PainelLoginAluno.setLayout(PainelLoginAlunoLayout);
        PainelLoginAlunoLayout.setHorizontalGroup(
            PainelLoginAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelLoginAlunoLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(PainelLoginAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(PainelLoginAlunoLayout.createSequentialGroup()
                        .addComponent(botaoVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoAcessarAluno))
                    .addComponent(labelSenhaAluno, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEmailAluno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textEmailAluno, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textSenhaAluno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );
        PainelLoginAlunoLayout.setVerticalGroup(
            PainelLoginAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelLoginAlunoLayout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(labelEmailAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textEmailAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelSenhaAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textSenhaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(PainelLoginAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAcessarAluno)
                    .addComponent(botaoVoltar))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelLoginAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelLoginAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAcessarAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAcessarAlunoMouseClicked
        LoginControlador controleLogin = new LoginControlador();
        String email = this.textEmailAluno.getText();
        String senha = String.copyValueOf(this.textSenhaAluno.getPassword());
        String respostaLoginAluno = controleLogin.verificaAluno(email, senha);
        
        if(respostaLoginAluno.equals("Sucesso no login")){
            JOptionPane.showMessageDialog(null, "Bem vindo ao sistema!");
            this.controlador.navegarParaMenuAluno();
            this.setVisible(false);
            dispose();
        }
        else{
            JOptionPane.showMessageDialog(null, "Acesso negado, verifique as credenciais!");
        }
    }//GEN-LAST:event_botaoAcessarAlunoMouseClicked

    private void botaoVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoVoltarMouseClicked
        this.controlador.navegarParaPrincipal();
        dispose();
    }//GEN-LAST:event_botaoVoltarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditorLoginAlunoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditorLoginAlunoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditorLoginAlunoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditorLoginAlunoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditorLoginAlunoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelLoginAluno;
    private javax.swing.JButton botaoAcessarAluno;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel labelEmailAluno;
    private javax.swing.JLabel labelSenhaAluno;
    private javax.swing.JTextField textEmailAluno;
    private javax.swing.JPasswordField textSenhaAluno;
    // End of variables declaration//GEN-END:variables
}