/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.castilho.paranavai.armario.visao;

import com.castilho.paranavai.armario.controle.EfetuarEmprestimoControladorGUI;
import static java.lang.reflect.Array.set;
import javax.swing.JOptionPane;

/**
 *
 * @author Wesley
 */
public class EfetuarEmprestimoGUI extends javax.swing.JFrame {

    private final EfetuarEmprestimoControladorGUI controlador;
    
    /**
     * Creates new form EfetuarEmprestimoGUI
     */
    public EfetuarEmprestimoGUI() {
        initComponents();
        this.setResizable(false);
        setTitle("Efetuar empréstimo");
        this.controlador = new EfetuarEmprestimoControladorGUI(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelFundoEmprestimo = new javax.swing.JPanel();
        labelEmprestimo = new javax.swing.JLabel();
        painelConteudo = new javax.swing.JPanel();
        labelAluno = new javax.swing.JLabel();
        textAluno = new javax.swing.JTextField();
        labelRa = new javax.swing.JLabel();
        textRa = new javax.swing.JTextField();
        labelLocalizacao = new javax.swing.JLabel();
        comboBoxLocal = new javax.swing.JComboBox<>();
        labelNumArmario = new javax.swing.JLabel();
        comboNumArmario = new javax.swing.JComboBox<>();
        labelCurso = new javax.swing.JLabel();
        textCurso = new javax.swing.JTextField();
        labelAno = new javax.swing.JLabel();
        comboAno = new javax.swing.JComboBox<>();
        labelData = new javax.swing.JLabel();
        textData = new javax.swing.JTextField();
        labelQtdeDiasEmprestimo = new javax.swing.JLabel();
        comboQtdeDiasEmprestimo = new javax.swing.JComboBox<>();
        checkResponsabilidade = new javax.swing.JCheckBox();
        botaoFinalizar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        botaoFinalizarEContinuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        painelFundoEmprestimo.setBackground(new java.awt.Color(204, 204, 204));
        painelFundoEmprestimo.setOpaque(false);

        labelEmprestimo.setBackground(new java.awt.Color(204, 255, 204));
        labelEmprestimo.setFont(new java.awt.Font("Calisto MT", 0, 24)); // NOI18N
        labelEmprestimo.setForeground(new java.awt.Color(51, 51, 255));
        labelEmprestimo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEmprestimo.setText("Realizar empréstimo:");
        labelEmprestimo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelEmprestimo.setOpaque(true);

        painelConteudo.setBackground(new java.awt.Color(204, 255, 204));
        painelConteudo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelAluno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelAluno.setText("Aluno:");

        textAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAlunoActionPerformed(evt);
            }
        });

        labelRa.setText("RA:");

        labelLocalizacao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelLocalizacao.setText("Localização:");

        comboBoxLocal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Biblioteca", "Bloco administrativo", "Bloco 02", "Bloco 03" }));

        labelNumArmario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelNumArmario.setText("Numeração do armário:");

        comboNumArmario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10" }));

        labelCurso.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelCurso.setText("Curso:");

        labelAno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelAno.setText("Ano:");

        comboAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primeiro ano", "Segundo ano", "Terceiro ano", "Quarto ano" }));

        labelData.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelData.setText("Data:");

        labelQtdeDiasEmprestimo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelQtdeDiasEmprestimo.setText("Quantidade de dias de empréstimo:");

        comboQtdeDiasEmprestimo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        checkResponsabilidade.setBackground(new java.awt.Color(204, 255, 204));
        checkResponsabilidade.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        checkResponsabilidade.setText("Eu me responsabilizo com a chave do armário escolhido");

        botaoFinalizar.setText("Finalizar");
        botaoFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFinalizarActionPerformed(evt);
            }
        });

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        botaoFinalizarEContinuar.setText("Finalizar e continuar");
        botaoFinalizarEContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFinalizarEContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelConteudoLayout = new javax.swing.GroupLayout(painelConteudo);
        painelConteudo.setLayout(painelConteudoLayout);
        painelConteudoLayout.setHorizontalGroup(
            painelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConteudoLayout.createSequentialGroup()
                .addGroup(painelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelConteudoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelConteudoLayout.createSequentialGroup()
                                .addComponent(labelAluno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelRa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textRa))
                            .addGroup(painelConteudoLayout.createSequentialGroup()
                                .addGroup(painelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(painelConteudoLayout.createSequentialGroup()
                                        .addComponent(labelLocalizacao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboBoxLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelNumArmario)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboNumArmario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelConteudoLayout.createSequentialGroup()
                                        .addComponent(labelCurso)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(labelAno)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(comboAno, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(painelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelConteudoLayout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(labelData)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textData))
                                    .addGroup(painelConteudoLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(labelQtdeDiasEmprestimo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboQtdeDiasEmprestimo, 0, 120, Short.MAX_VALUE))))))
                    .addGroup(painelConteudoLayout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addGroup(painelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelConteudoLayout.createSequentialGroup()
                                .addComponent(botaoCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoFinalizar)
                                .addGap(42, 42, 42)
                                .addComponent(botaoFinalizarEContinuar))
                            .addComponent(checkResponsabilidade, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelConteudoLayout.setVerticalGroup(
            painelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConteudoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAluno)
                    .addComponent(textAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRa)
                    .addComponent(textRa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(painelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCurso)
                    .addComponent(textCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAno)
                    .addComponent(comboAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelData)
                    .addComponent(textData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(painelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLocalizacao)
                    .addComponent(comboBoxLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNumArmario)
                    .addComponent(comboNumArmario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelQtdeDiasEmprestimo)
                    .addComponent(comboQtdeDiasEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107)
                .addComponent(checkResponsabilidade)
                .addGap(92, 92, 92)
                .addGroup(painelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoFinalizar)
                    .addComponent(botaoCancelar)
                    .addComponent(botaoFinalizarEContinuar))
                .addGap(104, 104, 104))
        );

        javax.swing.GroupLayout painelFundoEmprestimoLayout = new javax.swing.GroupLayout(painelFundoEmprestimo);
        painelFundoEmprestimo.setLayout(painelFundoEmprestimoLayout);
        painelFundoEmprestimoLayout.setHorizontalGroup(
            painelFundoEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFundoEmprestimoLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(painelFundoEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelFundoEmprestimoLayout.createSequentialGroup()
                        .addComponent(painelConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelFundoEmprestimoLayout.createSequentialGroup()
                        .addComponent(labelEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(324, 324, 324))))
        );
        painelFundoEmprestimoLayout.setVerticalGroup(
            painelFundoEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFundoEmprestimoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(painelConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFundoEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFundoEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAlunoActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void botaoFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFinalizarActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Empréstimo finalizado!");
        dispose();
    }//GEN-LAST:event_botaoFinalizarActionPerformed

    private void botaoFinalizarEContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFinalizarEContinuarActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Empréstimo finalizado, vamos para o próximo!");
        this.controlador.navegarParaEmprestimoNovamente();
        dispose();
    }//GEN-LAST:event_botaoFinalizarEContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EfetuarEmprestimoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EfetuarEmprestimoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EfetuarEmprestimoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EfetuarEmprestimoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EfetuarEmprestimoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoFinalizar;
    private javax.swing.JButton botaoFinalizarEContinuar;
    private javax.swing.JCheckBox checkResponsabilidade;
    private javax.swing.JComboBox<String> comboAno;
    private javax.swing.JComboBox<String> comboBoxLocal;
    private javax.swing.JComboBox<String> comboNumArmario;
    private javax.swing.JComboBox<String> comboQtdeDiasEmprestimo;
    private javax.swing.JLabel labelAluno;
    private javax.swing.JLabel labelAno;
    private javax.swing.JLabel labelCurso;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelEmprestimo;
    private javax.swing.JLabel labelLocalizacao;
    private javax.swing.JLabel labelNumArmario;
    private javax.swing.JLabel labelQtdeDiasEmprestimo;
    private javax.swing.JLabel labelRa;
    private javax.swing.JPanel painelConteudo;
    private javax.swing.JPanel painelFundoEmprestimo;
    private javax.swing.JTextField textAluno;
    private javax.swing.JTextField textCurso;
    private javax.swing.JTextField textData;
    private javax.swing.JTextField textRa;
    // End of variables declaration//GEN-END:variables
}