package com.castilho.paranavai.armario.visao;

import com.castilho.paranavai.armario.controle.EfetuarDevolucaoControlador;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Wesley
 */
public class EfetuarDevolucaoGUI extends javax.swing.JFrame {

    private final EfetuarDevolucaoControlador controlador;
    
    /**
     * Creates new form EfetuarDevolucaoGUI
     */
    public EfetuarDevolucaoGUI() {
        initComponents();
        this.setResizable(false);
        setTitle("Efetuar devolução");
        this.controlador = new EfetuarDevolucaoControlador(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelFundoDevolucao = new javax.swing.JPanel();
        labelTituloDevolucao = new javax.swing.JLabel();
        painelConteudoDevolucao = new javax.swing.JPanel();
        labelAlunoDev = new javax.swing.JLabel();
        textAlunoDev = new javax.swing.JTextField();
        labelRaDev = new javax.swing.JLabel();
        textRaDev = new javax.swing.JTextField();
        labelCursoDev = new javax.swing.JLabel();
        textCursoDev = new javax.swing.JTextField();
        labelAnoDev = new javax.swing.JLabel();
        comboAnoDev = new javax.swing.JComboBox<>();
        labelDataDev = new javax.swing.JLabel();
        textDataDev = new javax.swing.JTextField();
        labelLocalDev = new javax.swing.JLabel();
        comboLocalDev = new javax.swing.JComboBox<>();
        labelNumArmDev = new javax.swing.JLabel();
        comboNumArmDev = new javax.swing.JComboBox<>();
        checkEntregue = new javax.swing.JCheckBox();
        botaoCancelar = new javax.swing.JButton();
        botaoFinalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        painelFundoDevolucao.setOpaque(false);

        labelTituloDevolucao.setBackground(new java.awt.Color(204, 255, 204));
        labelTituloDevolucao.setFont(new java.awt.Font("Calisto MT", 0, 24)); // NOI18N
        labelTituloDevolucao.setForeground(new java.awt.Color(51, 51, 255));
        labelTituloDevolucao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloDevolucao.setText("Realizar devolução:");
        labelTituloDevolucao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelTituloDevolucao.setMaximumSize(new java.awt.Dimension(226, 28));
        labelTituloDevolucao.setMinimumSize(new java.awt.Dimension(226, 28));
        labelTituloDevolucao.setOpaque(true);
        labelTituloDevolucao.setPreferredSize(new java.awt.Dimension(226, 28));

        painelConteudoDevolucao.setBackground(new java.awt.Color(204, 255, 204));
        painelConteudoDevolucao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        painelConteudoDevolucao.setPreferredSize(new java.awt.Dimension(854, 543));

        labelAlunoDev.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelAlunoDev.setText("Aluno:");

        labelRaDev.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelRaDev.setText("RA:");

        labelCursoDev.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelCursoDev.setText("Curso:");

        labelAnoDev.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelAnoDev.setText("Ano:");

        comboAnoDev.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primeiro ano", "Segundo ano", "Terceiro ano", "Quarto ano" }));

        labelDataDev.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelDataDev.setText("Data da devolução:");

        labelLocalDev.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelLocalDev.setText("Localização:");

        comboLocalDev.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Biblioteca", "Bloco administrativo", "Bloco 02", "Bloco 03" }));

        labelNumArmDev.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelNumArmDev.setText("Numeracao do armário devolvido:");

        comboNumArmDev.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10" }));

        checkEntregue.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        checkEntregue.setText("Chave entregue e em perfeitas condições");
        checkEntregue.setOpaque(false);

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        botaoFinalizar.setText("Finalizar");
        botaoFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelConteudoDevolucaoLayout = new javax.swing.GroupLayout(painelConteudoDevolucao);
        painelConteudoDevolucao.setLayout(painelConteudoDevolucaoLayout);
        painelConteudoDevolucaoLayout.setHorizontalGroup(
            painelConteudoDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConteudoDevolucaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelConteudoDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelConteudoDevolucaoLayout.createSequentialGroup()
                        .addComponent(labelAlunoDev)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textAlunoDev, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelRaDev)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textRaDev))
                    .addGroup(painelConteudoDevolucaoLayout.createSequentialGroup()
                        .addGroup(painelConteudoDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(painelConteudoDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelConteudoDevolucaoLayout.createSequentialGroup()
                                    .addComponent(labelLocalDev)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(comboLocalDev, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(83, 83, 83)
                                    .addComponent(labelNumArmDev)
                                    .addGap(18, 18, 18)
                                    .addComponent(comboNumArmDev, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelConteudoDevolucaoLayout.createSequentialGroup()
                                    .addComponent(labelCursoDev)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(textCursoDev, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(31, 31, 31)
                                    .addComponent(labelAnoDev)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(comboAnoDev, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(labelDataDev)))
                            .addGroup(painelConteudoDevolucaoLayout.createSequentialGroup()
                                .addGroup(painelConteudoDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(checkEntregue)
                                    .addGroup(painelConteudoDevolucaoLayout.createSequentialGroup()
                                        .addComponent(botaoCancelar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botaoFinalizar)))
                                .addGap(50, 50, 50)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textDataDev, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelConteudoDevolucaoLayout.setVerticalGroup(
            painelConteudoDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConteudoDevolucaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelConteudoDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAlunoDev)
                    .addComponent(textAlunoDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRaDev)
                    .addComponent(textRaDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(painelConteudoDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCursoDev)
                    .addComponent(textCursoDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAnoDev)
                    .addComponent(comboAnoDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDataDev)
                    .addComponent(textDataDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(painelConteudoDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLocalDev)
                    .addComponent(comboLocalDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNumArmDev)
                    .addComponent(comboNumArmDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(117, 117, 117)
                .addComponent(checkEntregue)
                .addGap(52, 52, 52)
                .addGroup(painelConteudoDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCancelar)
                    .addComponent(botaoFinalizar))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelFundoDevolucaoLayout = new javax.swing.GroupLayout(painelFundoDevolucao);
        painelFundoDevolucao.setLayout(painelFundoDevolucaoLayout);
        painelFundoDevolucaoLayout.setHorizontalGroup(
            painelFundoDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFundoDevolucaoLayout.createSequentialGroup()
                .addGroup(painelFundoDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelFundoDevolucaoLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(painelConteudoDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelFundoDevolucaoLayout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(labelTituloDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        painelFundoDevolucaoLayout.setVerticalGroup(
            painelFundoDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFundoDevolucaoLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(labelTituloDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelConteudoDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFundoDevolucao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFundoDevolucao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void botaoFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFinalizarActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Devolução finalizada!");
        dispose();
    }//GEN-LAST:event_botaoFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EfetuarDevolucaoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EfetuarDevolucaoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EfetuarDevolucaoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EfetuarDevolucaoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EfetuarDevolucaoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoFinalizar;
    private javax.swing.JCheckBox checkEntregue;
    private javax.swing.JComboBox<String> comboAnoDev;
    private javax.swing.JComboBox<String> comboLocalDev;
    private javax.swing.JComboBox<String> comboNumArmDev;
    private javax.swing.JLabel labelAlunoDev;
    private javax.swing.JLabel labelAnoDev;
    private javax.swing.JLabel labelCursoDev;
    private javax.swing.JLabel labelDataDev;
    private javax.swing.JLabel labelLocalDev;
    private javax.swing.JLabel labelNumArmDev;
    private javax.swing.JLabel labelRaDev;
    private javax.swing.JLabel labelTituloDevolucao;
    private javax.swing.JPanel painelConteudoDevolucao;
    private javax.swing.JPanel painelFundoDevolucao;
    private javax.swing.JTextField textAlunoDev;
    private javax.swing.JTextField textCursoDev;
    private javax.swing.JTextField textDataDev;
    private javax.swing.JTextField textRaDev;
    // End of variables declaration//GEN-END:variables
}