/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.castilho.paranavai.armario.visao;

/**
 *
 * @author Wesley
 */
public class ListagemBibliotecarioGUI extends javax.swing.JFrame {

    /**
     * Creates new form ListagemBibliotecarioGUI
     */
    public ListagemBibliotecarioGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelSuperiorBibliotecario = new javax.swing.JPanel();
        lblSiape = new javax.swing.JLabel();
        txtSiape = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnNovoBibliotecario = new javax.swing.JButton();
        btnEditarBibliotecario = new javax.swing.JButton();
        btnCancelarBibliotecario = new javax.swing.JButton();
        painelInferiorBibliotecario = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaBibliotecario = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSiape.setText("SIAPE:");

        btnBuscar.setText("Buscar");

        btnNovoBibliotecario.setText("Novo");

        btnEditarBibliotecario.setText("Editar");
        btnEditarBibliotecario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarBibliotecarioActionPerformed(evt);
            }
        });

        btnCancelarBibliotecario.setText("Cancelar");

        javax.swing.GroupLayout painelSuperiorBibliotecarioLayout = new javax.swing.GroupLayout(painelSuperiorBibliotecario);
        painelSuperiorBibliotecario.setLayout(painelSuperiorBibliotecarioLayout);
        painelSuperiorBibliotecarioLayout.setHorizontalGroup(
            painelSuperiorBibliotecarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSuperiorBibliotecarioLayout.createSequentialGroup()
                .addGroup(painelSuperiorBibliotecarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelSuperiorBibliotecarioLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblSiape)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSiape, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(painelSuperiorBibliotecarioLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnNovoBibliotecario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditarBibliotecario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addGroup(painelSuperiorBibliotecarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelSuperiorBibliotecarioLayout.createSequentialGroup()
                        .addComponent(btnBuscar)
                        .addContainerGap(78, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelSuperiorBibliotecarioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelarBibliotecario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        painelSuperiorBibliotecarioLayout.setVerticalGroup(
            painelSuperiorBibliotecarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSuperiorBibliotecarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelSuperiorBibliotecarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painelSuperiorBibliotecarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSiape)
                        .addComponent(btnBuscar))
                    .addComponent(lblSiape, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(painelSuperiorBibliotecarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoBibliotecario)
                    .addComponent(btnEditarBibliotecario)
                    .addComponent(btnCancelarBibliotecario))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(painelSuperiorBibliotecario, java.awt.BorderLayout.PAGE_START);

        painelInferiorBibliotecario.setLayout(new java.awt.BorderLayout());

        tabelaBibliotecario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "SIAPE", "Ativo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaBibliotecario);

        painelInferiorBibliotecario.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(painelInferiorBibliotecario, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarBibliotecarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarBibliotecarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarBibliotecarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListagemBibliotecarioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListagemBibliotecarioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListagemBibliotecarioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListagemBibliotecarioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListagemBibliotecarioGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelarBibliotecario;
    private javax.swing.JButton btnEditarBibliotecario;
    private javax.swing.JButton btnNovoBibliotecario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSiape;
    private javax.swing.JPanel painelInferiorBibliotecario;
    private javax.swing.JPanel painelSuperiorBibliotecario;
    private javax.swing.JTable tabelaBibliotecario;
    private javax.swing.JTextField txtSiape;
    // End of variables declaration//GEN-END:variables
}
