/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.castilho.paranavai.armario.visao;

import com.castilho.paranavai.armario.controle.MenuAlunoControladorGUI;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Wesley
 */
public class MenuAlunoGUI extends javax.swing.JFrame {

    private final MenuAlunoControladorGUI controlador;     
    
    /**
     * Creates new form MenuAluno
     */
    public MenuAlunoGUI() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setTitle("iReservationSystem");
        this.controlador = new MenuAlunoControladorGUI(this);
        
        //telaNew = new FundoTelaNew("/assets/biblioteca.jpg");
        //getContentPane().add(telaNew);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelMenuAluno =  new JPanel() {  
            public void paintComponent(Graphics g) {  
                System.out.println(IndexGUI.class.getResource("/assets/biblioteca.jpg")); 
                Image img = Toolkit.getDefaultToolkit().getImage(IndexGUI.class.getResource("/assets/biblioteca.jpg"));  
                g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), this);  
            }  
        };
        alunoBarraMenu = new javax.swing.JMenuBar();
        alunoMenuMinhaConta = new javax.swing.JMenu();
        alunoMinhaContaMeusDados = new javax.swing.JMenuItem();
        alunoMinhaContaEmprestimosEfetuados = new javax.swing.JMenuItem();
        alunoMinhaContaSair = new javax.swing.JMenuItem();
        alunoMenuEmprestimo = new javax.swing.JMenu();
        emprestimoEfetuar = new javax.swing.JMenuItem();
        emprestimoCancelar = new javax.swing.JMenuItem();
        alunoMenuDevolucao = new javax.swing.JMenu();
        devolucaoEfetuar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout painelMenuAlunoLayout = new javax.swing.GroupLayout(painelMenuAluno);
        painelMenuAluno.setLayout(painelMenuAlunoLayout);
        painelMenuAlunoLayout.setHorizontalGroup(
            painelMenuAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 873, Short.MAX_VALUE)
        );
        painelMenuAlunoLayout.setVerticalGroup(
            painelMenuAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
        );

        alunoMenuMinhaConta.setText("Minha conta");
        alunoMenuMinhaConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alunoMenuMinhaContaActionPerformed(evt);
            }
        });

        alunoMinhaContaMeusDados.setText("Meus dados");
        alunoMenuMinhaConta.add(alunoMinhaContaMeusDados);

        alunoMinhaContaEmprestimosEfetuados.setText("Empréstimos efetuados");
        alunoMenuMinhaConta.add(alunoMinhaContaEmprestimosEfetuados);

        alunoMinhaContaSair.setText("Sair");
        alunoMinhaContaSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alunoMinhaContaSairMouseClicked(evt);
            }
        });
        alunoMinhaContaSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alunoMinhaContaSairActionPerformed(evt);
            }
        });
        alunoMenuMinhaConta.add(alunoMinhaContaSair);

        alunoBarraMenu.add(alunoMenuMinhaConta);

        alunoMenuEmprestimo.setText("Empréstimo");

        emprestimoEfetuar.setText("Efetuar empréstimo");
        emprestimoEfetuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emprestimoEfetuarActionPerformed(evt);
            }
        });
        alunoMenuEmprestimo.add(emprestimoEfetuar);

        emprestimoCancelar.setText("Cancelar empréstimo");
        alunoMenuEmprestimo.add(emprestimoCancelar);

        alunoBarraMenu.add(alunoMenuEmprestimo);

        alunoMenuDevolucao.setText("Devolução");

        devolucaoEfetuar.setText("Efetuar devolução");
        devolucaoEfetuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devolucaoEfetuarActionPerformed(evt);
            }
        });
        alunoMenuDevolucao.add(devolucaoEfetuar);

        alunoBarraMenu.add(alunoMenuDevolucao);

        setJMenuBar(alunoBarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelMenuAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelMenuAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void devolucaoEfetuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolucaoEfetuarActionPerformed
        this.controlador.navegarParaEfetuarDevolucao();
    }//GEN-LAST:event_devolucaoEfetuarActionPerformed

    private void alunoMenuMinhaContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alunoMenuMinhaContaActionPerformed
        
    }//GEN-LAST:event_alunoMenuMinhaContaActionPerformed

    private void alunoMinhaContaSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alunoMinhaContaSairMouseClicked
        
    }//GEN-LAST:event_alunoMinhaContaSairMouseClicked

    private void alunoMinhaContaSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alunoMinhaContaSairActionPerformed
        this.controlador.navegarParaLoginAluno();
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_alunoMinhaContaSairActionPerformed

    private void emprestimoEfetuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emprestimoEfetuarActionPerformed
        this.controlador.navegarParaEfetuarEmprestimo();
    }//GEN-LAST:event_emprestimoEfetuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAlunoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAlunoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAlunoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAlunoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAlunoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar alunoBarraMenu;
    private javax.swing.JMenu alunoMenuDevolucao;
    private javax.swing.JMenu alunoMenuEmprestimo;
    private javax.swing.JMenu alunoMenuMinhaConta;
    private javax.swing.JMenuItem alunoMinhaContaEmprestimosEfetuados;
    private javax.swing.JMenuItem alunoMinhaContaMeusDados;
    private javax.swing.JMenuItem alunoMinhaContaSair;
    private javax.swing.JMenuItem devolucaoEfetuar;
    private javax.swing.JMenuItem emprestimoCancelar;
    private javax.swing.JMenuItem emprestimoEfetuar;
    private javax.swing.JPanel painelMenuAluno;
    // End of variables declaration//GEN-END:variables
}